### PR TITLE
Shapeless page and black dye

### PR DESCRIPTION
**Pull request by MR-Spagetty**
changed the recipe for the notebook page to be shapeless and accept any black dye instead of just ink sacks

### CODE REVIEW

**Comment by MineDragonCZ** [comment]
Can not merge, because other mods can use same recipe.

**Comment by MR-Spagetty** [comment]
such as?

**Comment by MR-Spagetty** [comment]
what other mods use a shapless recipe of just paper black dye and a flower

**Comment by MineDragonCZ** [comment]
Idk, but it can

**Pull request closed without merging**
